title: All About it...
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.6864831
favicon: null
name: 'Graphic '
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.7328289
  lightness: 0.4645869
  saturation: 0.5738423
  rhythmicContrast: 0.3937605
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.9681029
