layout_spectrum: 0.719866
typography_spectrum: 0.9681029
color:
  lightness: 0.2403544
  brandStrength: 0.7328289
  saturation: 0.1558562
  rhythmicContrast: 0.5422725
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: 'Graphic '
